meta_data:
  script_path: /h/kamyar/oorl_rlkit/run_scripts/bc_train_script.py
  exp_dirs: /scratch/gobi2/kamyar/oorl_rlkit/output/
  exp_name: correct_larger_object_range_easy_in_the_air_fetch_bc
  description: searching over the SAC hyperparameters
  use_gpu: false
  num_workers: 12
  cpu_range: [0,159]
  num_cpu_per_worker: 1
# -----------------------------------------------------------------------------
variables:
  concat_env_params_to_obs: [false]

  expert_name: [
    # good_halfcheetah_100_trajs_1_subsampling,
    # good_halfcheetah_100_trajs_20_subsampling
    # dmcs_with_finger_pos_and_sin_cos_simple_meta_reacher_100_trajs_1_subsampling
    # original_fetch_pick_and_place_100_demos
    # my_noisy_fetch_100_demos
    # easy_fetch_0p01_range_1_goal_high_prob
    # easy_fetch_0p01_range_1_goal_high_prob_1000_clipped_demos
    # super_easy_fetch_1000_demos
    # max_ent_fetch_1000_demos
    # easy_in_the_air_1000_demos
    # larger_z_range_easy_in_the_air_1000_demos
    # larger_x_y_range_easy_in_the_air_1000_demos
    larger_object_range_easy_in_the_air_1000_demos
  ]

  bc_params:
    batch_size: [1024]
    # lr: [0.0003, 0.001]
    lr: [0.0003]
    # lr: [0.001]
    # use_layer_norm: [true, false]
    use_layer_norm: [false]

  env_specs:
    normalized: [false]
    train_test_env: [false]
  
  policy_net_size: [100, 256]
  num_policy_layers: [2, 3 , 4]
  
  seed: [9783, 5914]
  # seed: [9783]
  # seed: [5914, 4865, 2135, 2349]

# -----------------------------------------------------------------------------
constants:
  # expert_save_dict: '/ais/gobi6/kamyar/oorl_rlkit/output/final-pendulum-new-sac-hyper-param-search/final_pendulum_new_sac_hyper_param_search_2018_10_12_19_11_09_0000--s-0/extra_data.pkl'
  # last_k_expert_steps: 500
  expert_seed_run_idx: 0
  wrap_absorbing_state: false
  
  bc_params:
    max_iters: 200001
    num_steps_per_eval: 3500 # 70*50
    max_path_length: 70

    # batch_size: 100

    policy_uses_pixels: false
    policy_uses_task_params: false
    concat_task_params_to_policy_obs: false

    policy_mean_reg_weight: 0.001
    policy_std_reg_weight: 0.001
    policy_pre_activation_weight: 0.0

    freq_eval: 2500
    freq_saving: 10000
  
    
  env_specs:
    base_env_name: 'scaled_and_wrapped_target_in_air_easy'
