meta_data:
  script_path: /u/kamyar/oorl_rlkit/run_scripts/sac.py
  exp_dirs: /ais/gobi6/kamyar/oorl_rlkit/output
  exp_name: fixed_fetch_anywhere_reach_10x_shaping
  description: searching over the SAC hyperparameters
  use_gpu: false
  num_workers: 20
  cpu_range: [0,20]
  num_cpu_per_worker: 1
# -----------------------------------------------------------------------------
variables:
  algo_params:
    no_terminal: [false]
    num_updates_per_env_step: [1]
    reward_scale: [1.0, 5.0, 10.0, 25.0, 50.0, 100.0, 250.0, 500.0, 750.0, 1000.0]
    soft_target_tau: [0.005]
  
  env_specs:
    # base_env_name: ['fetch_reacher_v1']
    normalized: [false]
    train_test_env: [false]
  
  seed: [9783, 5914]
  # seed: [9783]

# -----------------------------------------------------------------------------
constants:
  algo_params:
    replay_buffer_size: 600000

    num_epochs: 501
    num_steps_per_epoch: 1200
    num_steps_per_eval: 1200
    batch_size: 256
    max_path_length: 60
    discount: 0.99

    policy_lr: 0.0003
    qf_lr: 0.0003
    vf_lr: 0.0003
    policy_mean_reg_weight: 0.001
    policy_std_reg_weight: 0.001

    policy_uses_pixels: false
    policy_uses_task_params: true
    concat_task_params_to_policy_obs: true

    render: false

    save_replay_buffer: false
    save_environment: false
    freq_saving: 50
  
  net_size: 256
  
  env_specs:
    base_env_name: 'rotated_no_head_fetch_reach_anywhere'
