meta_data:
  script_path: /u/kamyar/oorl_rlkit/gen_models/train_new_vrnn.py
  exp_dirs: /ais/gobi6/kamyar/oorl_rlkit/output
  exp_name: debug_vrnn
  description: VRNN
  num_workers: 1
  cpu_range: [0,1]
  num_cpu_per_worker: 1

# -----------------------------------------------------------------------------
variables:
  seed: [9783]
  # seed: [9783, 5914, 4865, 2135, 2349]

# -----------------------------------------------------------------------------
constants:
  use_gpu: true

  episode_length: 8
  batch_size: 64

  model_lr: 1e-4
  model_wd: 0
  freq_bptt: 8
  freq_val: 1000
  max_iters: 160000

  vrnn_specs:
    z_dim: 512
    act_proc_dim: 64
    pre_post_gru_dim: 512

    x_encoder_specs:
      kernel_sizes: [4, 4, 1, 1]
      num_channels: [32, 32, 32, 32]
      strides: [2, 2, 1, 1]
      paddings: [1, 1, 0, 0]
      use_bn: true
    
    decoder_part_specs:
      kernel_sizes: [4, 4]
      num_channels: [32, 32]
      strides: [2, 2]
      paddings: [1, 1]
      output_paddings: [0, 0]
      use_bn: true

# 32, 128, 512 for 3x3
# 32, 512, 2048 for 5x5
