meta_data:
  script_path: /u/kamyar/oorl_rlkit/gen_models/train_attentive_vae.py
  exp_dirs: /ais/gobi6/kamyar/oorl_rlkit/output
  exp_name: debug_att_vae
  description: Attentive VAE
  num_workers: 1
  cpu_range: [0,1]
  num_cpu_per_worker: 1

# -----------------------------------------------------------------------------
variables:
  seed: [9783]
  # seed: [9783, 5914, 4865, 2135, 2349]

# -----------------------------------------------------------------------------
constants:
  use_gpu: true

  batch_size: 64

  model_lr: 1e-4
  model_wd: 0
  freq_val: 1000
  epochs: 1000

  vae_specs:
    z_dim: 64

    x_encoder_specs:
      kernel_sizes: [3, 3]
      num_channels: [64, 64]
      strides: [2, 2]
      paddings: [1, 1]
      use_bn: true
    
    z_seg_conv_specs:
      kernel_sizes: [3, 3]
      num_channels: [64, 64]
      strides: [1, 1]
      paddings: [1, 1]
      use_bn: true
    
    z_seg_fc_specs:
      hidden_sizes: [1024]
      use_bn: true
    
    z_obj_conv_specs:
      kernel_sizes: [3]
      num_channels: [64]
      strides: [2]
      paddings: [1]
      use_bn: true

    z_obj_fc_specs:
      hidden_sizes: [1024]
      use_bn: true
    
    z_seg_recon_fc_specs:
      hidden_sizes: [1024, 9216]
      use_bn: true
    
    z_seg_recon_upconv_specs:
      kernel_sizes: [3]
      num_channels: [64]
      strides: [1]
      paddings: [1]
      output_paddings: [0]
      use_bn: true
    
    z_obj_recon_fc_specs:
      hidden_sizes: [1024, 9216]
      use_bn: true
    
    z_obj_recon_upconv_specs:
      kernel_sizes: [3]
      num_channels: [64]
      strides: [2]
      paddings: [1]
      output_paddings: [0]
      use_bn: true

    recon_upconv_part_specs:
      kernel_sizes: [4, 4]
      num_channels: [64, 64]
      strides: [2, 2]
      paddings: [1, 1]
      output_paddings: [0, 0]
      use_bn: true
