meta_data:
  script_path: /u/kamyar/oorl_rlkit/gen_models/train_onthefly_conv_lstm.py
  exp_dirs: /ais/gobi6/kamyar/oorl_rlkit/output
  exp_name: debug_vrnn
  description: flat VRNN
  num_workers: 1
  cpu_range: [0,1]
  num_cpu_per_worker: 1

# -----------------------------------------------------------------------------
variables:
  seed: [9783]
  # seed: [9783, 5914, 4865, 2135, 2349]

# -----------------------------------------------------------------------------
constants:
  # flat_vrnn: true
  # flat_latent: true
  use_gpu: true

  # replay_dict_path: /ais/gobi6/kamyar/oorl_rlkit/maze_trans_data/fixed_colors_new_mem_grid_scale_4
  # replay_dict_path: /ais/gobi6/kamyar/oorl_rlkit/maze_trans_data/pogrid_len_8_scale_4
  episode_length: 8
  batch_size: 64

  model_lr: 1e-4
  model_wd: 0
  freq_bptt: 8
  freq_val: 500
  max_iters: 160000

  # vrnn_specs:
  #   masked_latent: false
  #   z_dim: 32
  #   act_proc_dim: 32

  #   x_encoder_specs:
  #     hidden_sizes: [64, 64]
  #     use_bn: true
    
  #   pre_gru_specs:
  #     hidden_sizes: [128, 128]
  #     use_bn: true
    
  #   gru_specs:
  #     hidden_size: 128
    
  #   prior_part_specs:
  #     hidden_sizes: [128, 129]
  #     use_bn: true
    
  #   inference_part_specs:
  #     hidden_sizes: [128, 128]
  #     use_bn: true
    
  #   decoder_part_specs:
  #     fc_part:
  #       hidden_sizes: [128, 128, 128]
  #       use_bn: true


# 32, 128, 512 for 3x3
# 32, 512, 2048 for 5x5
