meta_data:
  script_path: /u/kamyar/oorl_rlkit/gen_models/train_normal_vae.py
  exp_dirs: /ais/gobi6/kamyar/oorl_rlkit/output
  exp_name: debug_att_vae
  description: Attentive VAE
  num_workers: 1
  cpu_range: [0,1]
  num_cpu_per_worker: 1

# -----------------------------------------------------------------------------
variables:
  seed: [9783]
  # seed: [9783, 5914, 4865, 2135, 2349]

# -----------------------------------------------------------------------------
constants:
  use_gpu: true

  masked: true

  batch_size: 16

  model_lr: 1e-4
  model_wd: 0
  freq_val: 1000
  epochs: 1000

  vae_specs:
    z_dim: 128

    encoder_specs:
      conv_part_specs:
        kernel_sizes: [3, 3]
        num_channels: [64, 64]
        strides: [2, 2]
        paddings: [1, 1]
        use_bn: true
      # output is 9*9*64=3136 dim

      fc_part_specs:
        hidden_sizes: [1024]
        use_bn: true

    decoder_specs:
      fc_part_specs:
        hidden_sizes: [1024, 5184]
        use_bn: true

      upconv_part_specs:
        kernel_sizes: [4, 4]
        num_channels: [64, 64]
        strides: [2, 2]
        paddings: [1, 1]
        output_paddings: [0, 0]
        use_bn: true



  # vae_specs:
  #   z_dim: 128

  #   encoder_specs:
  #     conv_part_specs:
  #       kernel_sizes: [5, 5, 5]
  #       num_channels: [64, 64, 64]
  #       strides: [2, 2, 2]
  #       paddings: [2, 2, 2]
  #       use_bn: true
  #     # output is 7*7*64=3136 dim

  #     fc_part_specs:
  #       hidden_sizes: [512]
  #       use_bn: true

  #   decoder_specs:
  #     fc_part_specs:
  #       hidden_sizes: [512, 3136]
  #       use_bn: true

  #     upconv_part_specs:
  #       kernel_sizes: [5, 5, 5]
  #       num_channels: [64, 64, 64]
  #       strides: [2, 2, 2]
  #       paddings: [2, 2, 2]
  #       output_paddings: [0, 0, 1]
  #       use_bn: true
