meta_data:
  script_path: /u/kamyar/oorl_rlkit/run_scripts/train_transition_regressor.py
  exp_dirs: /u/kamyar/oorl_rlkit/output
  exp_name: 150_300_range_meta_reacher_trans_regr
  description: we have to be at least beating this what the exp_name says LOL min 1000 samples per env gear setting
  num_workers: 28
  cpu_range: [4,31]
  num_cpu_per_worker: 1

# -----------------------------------------------------------------------------
variables:
  remove_env_info: [true, false]
  normalize_env_info: [true]
  env_info_range: [[150, 300]]

  train_set_size: [16000, 256000]
  seed: [9783, 5914]
  # seed: [9783, 5914, 4865, 2135, 2349]
  num_hidden_layers: [2, 4, 6, 8]
  train_from_beginning_transitions: [true, false]

# -----------------------------------------------------------------------------
constants:
  extra_data_path: /u/kamyar/oorl_rlkit/output/meta-reacher-robustness-check/meta_reacher_robustness_check_2018_08_09_16_45_05_0002--s-0/extra_data.pkl

  extra_obs_dim: 2

  residual: false

  hidden_dim: 128
  lr: 1e-3

  train_batch_size: 64
  val_batch_size: 1000

  val_set_size: 50000

  max_iters: 50000
  freq_val: 1000


# num_hidden_layers: 4
# hidden_dim: 128
# train_set_size: 100
# residual: true
# script_path: /u/kamyar/oorl_rlkit/run_scripts/train_transition_regressor.py
# exp_dirs: /u/kamyar/oorl_rlkit/output
# exp_name: debug_9999
# description: searching over the SAC hyperparameters
# exp_id: 0
