meta_data:
  script_path: /u/kamyar/oorl_rlkit/run_scripts/meta_sac.py
  exp_dirs: /u/kamyar/oorl_rlkit/output
  exp_name: meta_reacher_robustness_check
  description: searching over the SAC hyperparameters
  num_workers: 30
  cpu_range: [0,29]
  num_cpu_per_worker: 1
# -----------------------------------------------------------------------------
variables:
  algo_params:
    num_updates_per_env_step: [4]
    reward_scale: [5.0, 10.0]
  seed: [9783, 5914, 4865, 2135, 2349]
  epoch_to_start_training: [16, 32, 50]

# -----------------------------------------------------------------------------
constants:
  algo_params:
    concat_env_params_to_obs: true

    num_epochs: 1050
    num_steps_per_epoch: 1000
    num_steps_per_eval: 1000
    batch_size: 128
    max_path_length: 999
    discount: 0.99

    soft_target_tau: 0.01
    policy_lr: 0.0003
    qf_lr: 0.0003
    vf_lr: 0.0003

    render: false

    save_replay_buffer: true

  net_size: 128

  env_specs:
    base_env_name: 'meta_gears_reacher'
    gear_0: [150, 200, 250, 300]
    gear_1: [150, 200, 250, 300]
