meta_data:
  script_path: run_scripts/sac.py
  exp_name: test
  description: searching over the SAC hyperparameters
  use_gpu: true
  num_workers: 2
  cpu_range: [0,159]
  num_cpu_per_worker: 1
# -----------------------------------------------------------------------------
variables:
  # seed: [1553, 7972, 9361, 1901]
  seed: [1553, 7972]

# -----------------------------------------------------------------------------
constants:
  use_custom_ant_models: false
  algo_params:
    save_best: true
    save_best_starting_from_epoch: 80
    
    meta: false
    num_epochs: 201
    num_steps_per_epoch: 10
    num_steps_per_eval: 10000
    replay_buffer_size: 1000000

    num_updates_per_env_step: 1
    batch_size: 256
    reward_scale: 20
    # reward_scale: 5
    soft_target_tau: 0.005

    max_path_length: 1000
    discount: 0.99

    policy_lr: 0.0003
    qf_lr: 0.0003
    vf_lr: 0.0003
    policy_mean_reg_weight: 0.001
    policy_std_reg_weight: 0.001

    render: false
    save_algorithm: true
    freq_saving: 20

  net_size: 256
  num_hidden_layers: 2

  env_specs:
    base_env_name: 'humanoid_v2'
    normalized: false
    train_test_env: false
