meta_data:
  script_path: /u/kamyar/oorl_rlkit/run_scripts/meta_sac.py
  exp_dirs: /u/kamyar/oorl_rlkit/output
  exp_name: new_sac_ant
  description: searching over the SAC hyperparameters
  num_workers: 32
  cpu_range: [0,31]
  num_cpu_per_worker: 1

# -----------------------------------------------------------------------------
variables:
  use_new_sac: [true]
  algo_params:
    epoch_to_start_training: [10]
    concat_env_params_to_obs: [false]
    normalize_env_params: [false]
    num_updates_per_env_step: [1, 4]
    reward_scale: [1, 5]
    soft_target_tau: [0.005, 0.01]
  
  env_specs:
    normalized: [true, false]
  
  # seed: [9783, 5914, 4865, 2135, 2349]
  seed: [9783, 5914]

# -----------------------------------------------------------------------------
constants:
  algo_params:
    num_epochs: 1001
    num_steps_per_epoch: 1000
    num_steps_per_eval: 1000
    batch_size: 256
    max_path_length: 1000
    discount: 0.99

    policy_lr: 0.0003
    qf_lr: 0.0003
    vf_lr: 0.0003
    policy_mean_reg_weight: 0.001
    policy_std_reg_weight: 0.001

    render: false

    save_replay_buffer: true

  net_size: 256

  env_specs:
    base_env_name: 'ant_v1'
