meta_data:
  script_path: /u/kamyar/oorl_rlkit/gen_models/train_vrnn.py
  exp_dirs: /ais/gobi6/kamyar/oorl_rlkit/output
  exp_name: debug_vrnn
  description: VRNN
  num_workers: 1
  cpu_range: [0,1]
  num_cpu_per_worker: 1

# -----------------------------------------------------------------------------
variables:
  seed: [9783]
  # seed: [9783, 5914, 4865, 2135, 2349]

# -----------------------------------------------------------------------------
constants:
  use_gpu: true

  episode_length: 8
  batch_size: 64

  model_lr: 1e-4
  model_wd: 0
  freq_bptt: 8
  freq_val: 1000
  max_iters: 160000

  vrnn_specs:
    z_dim: 512
    act_proc_dim: 512
    lstm_dim: 2048

    x_encoder_specs:
      kernels: [1, 1, 1, 1]
      num_channels: [32, 32, 32, 32]
      strides: [1, 1, 1, 1]
      paddings: [0, 0, 0, 0]
      use_bn: true
    
    prior_part_specs:
      hidden_sizes: [128]
      use_bn: true
    
    inference_part_specs:
      hidden_sizes: [128, 128]
      use_bn: true
    
    decoder_part_specs:
      fc_part:
        hidden_sizes: [128, 128, 128]
        use_bn: true
      
      conv_part_specs:
        kernels: []
        num_channels: []
        strides: []
        paddings: []
        output_paddings: []
        use_bn: true


# 32, 128, 512 for 3x3
# 32, 512, 2048 for 5x5
