meta_data:
  exp_name: bug_free_pendulum_hyper_param_search
  description: searching over the SAC hyperparameters
  num_workers: 10
# -----------------------------------------------------------------------------
variables:
  algo_params:
    num_updates_per_env_step: [1, 4, 10]
    reward_scale: [0.5, 1.0, 5.0, 10.0, 20.0, 50.0, 100.0]

# -----------------------------------------------------------------------------
constants:
  algo_params:
    num_epochs: 200
    num_steps_per_epoch: 1000
    num_steps_per_eval: 1000
    batch_size: 128
    max_path_length: 999
    discount: 0.99

    soft_target_tau: 0.01
    policy_lr: 0.0003
    qf_lr: 0.0003
    vf_lr: 0.0003

    render: false

    save_replay_buffer: true
  
  net_size: 128
  
  env_specs:
    base_env_name: 'gravity_gear_inverted_pendulum'
    gravity: -9.81
    gear: 100
