meta_data:
  script_path: /u/kamyar/oorl_rlkit/run_scripts/bc_train_script.py
  exp_dirs: /ais/gobi6/kamyar/oorl_rlkit/output
  exp_name: simple_reacher_bc
  description: searching over the SAC hyperparameters
  use_gpu: false
  num_workers: 4
  cpu_range: [0,4]
  num_cpu_per_worker: 1
# -----------------------------------------------------------------------------
variables:
  concat_env_params_to_obs: [false]

  num_expert_trajs: [100]

  bc_params:
    batch_size: [100]

  env_specs:
    normalized: [false]
    train_test_env: [true]
  
  # seed: [9783, 5914]
  seed: [9783]

# -----------------------------------------------------------------------------
constants:
  # expert_save_dict: '/ais/gobi6/kamyar/oorl_rlkit/output/final-pendulum-new-sac-hyper-param-search/final_pendulum_new_sac_hyper_param_search_2018_10_12_19_11_09_0000--s-0/extra_data.pkl'
  # last_k_expert_steps: 500
  expert_name: temp_dmcs_with_finger_pos_and_sin_cos_simple_meta_reacher_100_trajs_1_subsampling
  expert_seed_run_idx: 4
  wrap_absorbing_state: false
  
  bc_params:
    max_iters: 500001
    num_steps_per_eval: 1000
    max_path_length: 100

    # batch_size: 100

    policy_uses_pixels: false
    policy_uses_task_params: true
    concat_task_params_to_policy_obs: true

    lr: 0.0003 # or 0.001
    policy_mean_reg_weight: 0.001
    policy_std_reg_weight: 0.001
    policy_pre_activation_weight: 0.0

    freq_eval: 1000
    freq_saving: 10000
  
  policy_net_size: 256
    
  env_specs:
    base_env_name: 'dmcs_simple_meta_reacher'
