meta_data:
  exp_fn_name: neural_processes_v1
  exp_dirs: /u/kamyar/oorl_rlkit/output
  exp_name: test_bug_free_np
  description: searching over the NPv1 hyperparameters
  num_workers: 1
# -----------------------------------------------------------------------------
variables:

# -----------------------------------------------------------------------------
constants:
  N_tasks : 100
  num_tasks_per_batch : 64
  choice_replace: true
  data_sampling_mode : constant
  num_per_task_low : 3
  num_per_task_high : 10
  max_iters : 10001
  lr: 1e-3

  aggregator : sum_aggregator
  z_dim : 5
  r_dim : 40

  use_bn : true
  num_enc_hid_layers: 4
  enc_hid_dim: 40
  num_base_map_hid_layers: 4
  base_map_hid_dim: 100
  num_r_to_z_map_hid_layers: 4
  r_to_z_map_hid_dim: 40

  freq_val : 100
