meta_data:
  script_path: /u/kamyar/oorl_rlkit/run_scripts/sac.py
  exp_dirs: /u/kamyar/oorl_rlkit/output
  exp_name: fast_reacher_hyper_param_search
  description: searching over the SAC hyperparameters
  num_workers: 14
  cpu_range: [0,13]
  num_cpu_per_worker: 1
# -----------------------------------------------------------------------------
variables:
  algo_params:
    num_updates_per_env_step: [1, 4]
    reward_scale: [0.5, 1.0, 5.0, 10.0, 25.0, 50.0, 100.0]

# -----------------------------------------------------------------------------
constants:
  algo_params:
    num_epochs: 500
    num_steps_per_epoch: 1000
    num_steps_per_eval: 1000
    batch_size: 128
    max_path_length: 999
    discount: 0.99

    soft_target_tau: 0.01
    policy_lr: 0.0003
    qf_lr: 0.0003
    vf_lr: 0.0003

    render: false

    save_replay_buffer: true
  
  net_size: 128

  true_meta_variable_names: ['gear', 'friction']
  true_meta_variable_dims: [[1], [1]]
  
  # env_specs:
  #   base_env_name: 'gravity_gear_inverted_pendulum'
  #   gravity: -9.81
  #   gear: 100
