meta_data:
  script_path: /u/kamyar/oorl_rlkit/gen_models/train_vae.py
  exp_dirs: /ais/gobi6/kamyar/oorl_rlkit/output
  exp_name: debug_vae
  description: VAE
  num_workers: 1
  cpu_range: [0,1]
  num_cpu_per_worker: 1

# -----------------------------------------------------------------------------
variables:
  seed: [9783]
  # seed: [9783, 5914, 4865, 2135, 2349]

# -----------------------------------------------------------------------------
constants:
  use_gpu: true
  use_masked_vae: true

  replay_dict_path: /ais/gobi6/kamyar/oorl_rlkit/maze_trans_data/trivial_grid_rand_policy_4
  episode_length: 50
  batch_size: 64

  model_lr: 1e-4
  model_wd: 0
  freq_val: 100
  max_iters: 10000
