meta_data:
  script_path: /u/kamyar/oorl_rlkit/gen_models/train_vrnn.py
  exp_dirs: /ais/gobi6/kamyar/oorl_rlkit/output
  exp_name: debug_vrnn
  description: VRNN
  num_workers: 1
  cpu_range: [0,1]
  num_cpu_per_worker: 1

# -----------------------------------------------------------------------------
variables:
  seed: [9783]
  # seed: [9783, 5914, 4865, 2135, 2349]

# -----------------------------------------------------------------------------
constants:
  use_gpu: true

  replay_dict_path: /ais/gobi6/kamyar/oorl_rlkit/maze_trans_data/trivial_grid_rand_policy_4
  episode_length: 10
  batch_size: 64

  model_lr: 1e-4
  model_wd: 0
  freq_bptt: 10
  freq_val: 500
  max_iters: 40000

  vrnn_specs:
    masked_latent: false
    z_dim: 32

    x_encoder_specs:
      kernel_sizes: [4, 4]
      num_channels: [32, 32]
      strides: [2, 2]
      paddings: [1, 1]
      use_bn: true
    
    gru_specs:
      kernel_size: 3
      num_channels: 32
    
    prior_part_specs:
      kernel_sizes: [3, 3]
      num_channels: [32, 32]
      strides: [1, 1]
      paddings: [1, 1]
      use_bn: true
    
    inference_part_specs:
      conv_part_specs:
        kernel_sizes: [3, 3]
        num_channels: [32, 32]
        strides: [1, 1]
        paddings: [1, 1]
        use_bn: true
      
      # fc_part_specs:
      #   hidden_sizes: [64, 64]
      #   use_bn: true
    
    # z_encoder_specs:
    #   kernel_sizes: [3, 3]
    #   num_channels: [32, 32]
    #   strides: [1, 1]
    #   paddings: [1, 1]
    #   use_bn: true
    
    decoder_part_specs:
      kernel_sizes: [4, 4]
      num_channels: [64, 64]
      strides: [2, 2]
      paddings: [1, 1]
      output_paddings: [0, 0]
      use_bn: true
